name: 'Setup Dune'
description: 'install/setup ocaml and dune'
branding:
  icon: 'box'
  color: 'orange'
inputs:
  packages:
    description: 'OPAM packages to install'
    required: false
    default: ''
  compiler:
    description: 'Compiler version to use'
    required: false
    default: 'stable'
runs:
  using: "composite"
  steps:
    - name: Install dune
      run: |
        sudo apt-get update
        sudo apt-get install opam
        opam init
        eval $(opam env --switch=default)
      shell: bash
    - name: Cache OPAM packages
      id: cache-opam
      uses: actions/cache@v3
      with:
        path: ~/.opam
        key: ${{ runner.os }}-${{ inputs.packages }}-opam
    - name: Install opam packages
      if: steps.cache-opam.outputs.cache-hit != 'true'
      run: |
        opam switch create ${{ inputs.compiler }}
        opam switch set ${{ inputs.compiler }}
        opam install dune ${{ inputs.packages }} -y
      shell: bash
    - name: Eval opem env
      run: echo "eval $(opam config env)" >> ~/.bash_profile
      shell: bash
